# This file will create a selenium hub container + 3 browsers containers
version: "3"
services:
  selenium-hub-warriors:
    image: selenium/hub:latest
    container_name: selenium-hub-warriors
    ports:
      - "4442:4443"
      - "4443:4443"
      - "4444:4444"

  chrome-node: ## this is the name of the service
    image: selenium/node-chrome:beta
    shm_size: 2gb
    ports:
      ## - "5555:5900" ## instead of static ports, we use dynamic ones as below to enable more than 1 chrome
      - "5555:5900"
      - "5900" ## review this
      - "7900" ## review this
      ## don't forget to scale the service
    depends_on:
      - selenium-hub-warriors
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub-warriors
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
       ## - SE_VNC_NO_PASSWORD=1

  firefox-node:
    image: selenium/node-firefox:beta
    shm_size: 2gb
    ports:
      - "5556:5900"
    depends_on:
      - selenium-hub-warriors
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub-warriors
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      ## - SE_VNC_NO_PASSWORD=1

  edge-node:
    image: selenium/node-edge:beta
    shm_size: 2gb
    ports:
      - "5557:5900"
    depends_on:
      - selenium-hub-warriors
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub-warriors
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ## - SE_VNC_NO_PASSWORD=1
