pipeline {
    agent any
    stages {
        stage("Clean up") {
            steps {
                deleteDir()
            }
        }
        stage("Clone Repo") {
            steps {
                sh 'git clone https://github.com/sguerrero11/Warriors.git'
            }
        }
        stage("Build") {
            steps {
                dir("Warriors") {
                    sh 'mvn clean install -U'
                }
            }
        }
        stage("Test") {
            steps {
                dir("Warriors") {
                    sh 'mvn test "-Dtest=FrontEnd.SauceDemo.LoginWithDP#readFromArray"'
                    // sh 'mvn test' // to run all tests in the project
                }
            }
        }
        stage("Complete") {
            steps {
                echo 'Complete'
            }
        }
    }
}