pipeline {
    agent any
    stages {
        stage("Clean up") {
            steps {
                deleteDir()
            }
        }
        stage("Clone Repo") {
            steps {
                sh 'git clone https://github.com/sguerrero11/Warriors.git'
            }
        }
        stage("Build") {
            steps {
                dir("Warriors") {
                    sh 'mvn clean install -X'
                }
            }
        }
        stage("Test") {
            steps {
                dir("Warriors") {
                    sh 'mvn test "-Dsurefire.failIfNoSpecifiedTests=false"'
                    sh 'mvn test "-Dtest=FrontEnd.SauceDemo.LoginWithDP" "-Dsurefire.failIfNoSpecifiedTests=false"'
                    sh 'mvn test "-Dtest=FrontEnd.SauceDemo.LoginWithDP#readFromArray" "-Dsurefire.failIfNoSpecifiedTests=false"'

                    // sh "${mvnHome}/bin/mvn clean test -e -Dtest=FrontEnd.SauceDemo.LoginWithDP#readFromArray"

                    //sh 'mvn test' // to run all tests in the project
                }
            }
        }
        stage("Complete") {
            steps {
                echo 'Complete'
            }
        }
    }
}