ebean:
  test:
    useDocker: true  # DO NOT USE DOCKER
    platform: postgres #, h2, postgres, mysql, oracle, sqlserver, hana, clickhouse, sqlite
    ddlMode: dropCreate # none | dropCreate | migrations | create
    dbName: test
    mysql:
      username: test
      password: test
      url: jdbc:postgresql://localhost:5432/test